# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g9Wo-nRLsTj09j4ijKVvS7zOyDbm6PKJ
"""

print("i am going to be a software engineer!")

course = 'Python for Begginers'

print (course.upper())

print (course.encode())

import random

secret_number =random.randint(1, 10)

print("i am thinking of a number between 1 and 10")

guess = int(input("take a guess:"))

if guess == secret_number:
  print('Brilliant! You guessed it right!')
else:
  print(f'Not quite! My number was actually{secret_number}.')

print("i am going to be a software engineer")

print (course.upper())

!pip install streamlit -q

"""%%writefile app.py

import streamlit as st
"""

st.title("My First Python Web App")

st.write("Welcome! This app was build entirely on a Chromebook")

st.header("currency converter")

ksh_amount = st.number_input("Enter amount in Kenyan Shillings(Ksh):")

usd_amount = ksh_amount / 130.0

st.success(f"That is approximately **${usd_amount:.2f} USD**")

st.header("Quick Math Challenge")

st.write("Since you love math, solve this:")

user_answer = st.number_input("What is 15 multiplied by 6?", min_value=0,)

if user_answer == 90:
    st.balloons()
    st.success("correct! outstanding job!")
elif user_answer != 0:
    st.error("Not quite right yet. Try again!")

!npx localtunnel --port 8501